# Generated by Django 4.2.30 on 2026-05-12 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("FARM", "Farm"), ("BUTCHERY", "Butchery")],
                        max_length=10,
                    ),
                ),
                (
                    "quantity_kg",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "minimum_threshold",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_records",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Inventories",
                "unique_together": {("product", "source_type")},
            },
        ),
    ]
